src/admin_panel/app/user/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', login_required(views.CustomUserList.as_view()), name='user-list'),
    path('create/', login_required(views.CreateCustomUserView.as_view()), name='user-create'),
    path('update/<int:pk>/', login_required(views.UpdateCustomUserView.as_view()), name='user-update'),
    path('delete/<int:pk>/', login_required(views.CustomUserDelete.as_view()), name='user-delete'),
]

src/api/urls.py
router.register(r'poster', site.PosterView, basename='poster-api')
router.register(r'top-quizz', quizz.QuizzView, basename='top-quiz-api')
router.register(r'link', site.UsefulLinkView, basename='link-api')

# About us page
router.register(r'about', about.AboutUsView, basename='about-api')
router.register(r'number_data_from_erp', about.IntegrationErpNumberDataView, basename='number_data_from_erp-api')

router.register(r'staff-list', about.StaffListView, basename='filter-staff-api')
router.register(r'structure', about.StructureView, basename='structure-api')
router.register(r'visitor', about.VisitorView, basename='visitor-api')

# Department & Organization
router.register(r'all-department', about.AllDepartmentView, basename='all-department-api')
router.register(r'department', about.DepartmentView, basename='department-api')
router.register(r'organizations', about.OrganizationView, basename='organization-api')
router.register(r'organization_type', about.OrganizationTypeView, basename='organization_type-api')

# Vacancy
router.register(r'vacancy', about.VacancyView, basename='vacancy-api')

# All staff and leaders
router.register(r'leader', about.StaffView, basename='leader-api')
router.register(r'leader-region', about.StaffRegionView, basename='leader-region-api')
router.register(r'leader-organization', about.StaffOrganizationView, basename='leader-organization-api')
router.register(r'leader-central', about.StaffCentralView, basename='leader-central-api')

# Press API
router.register(r'news', news.NewsListView, basename='news-api')
router.register(r'news-integration', news.NewsIntegration, basename='news-api-integration')
router.register(r'news-region', news.NewsRegionView, basename='news-region-api')
router.register(r'news-header', news.HeaderNewsListView, basename='news-header-api')
router.register(r'news-category', news.NewsCategoryView, basename='news-category-api')
router.register(r'news-hashtag', news.NewsHashtagView, basename='news-hashtag-api')
router.register(r'main-news', news.MainNewsListView, basename='main-api')
router.register(r'press', news.PressListView, basename='press-api')
router.register(r'faq', news.FAQListView, basename='faq-api')

# Static page
router.register(r'static', static.StaticView, basename='static-api')
router.register(r'static_data', static.StaticDataView, basename='static_data-api')

# Gallery
router.register(r'photo', gallery.PhotoListView, basename='photo-api')
router.register(r'video', gallery.VideoListView, basename='video-api')

# Event
router.register(r'event', event.EventListView, basename='event-api')

# Sport
router.register(r'stadion', sport.StadionListView, basename='sport-api')
router.register(r'champion', sport.ChampionView, basename='champion-api')
router.register(r'champion-list', sport.ChampionListView, basename='champion-list-api')

# Docs
router.register(r'docs', docs.DocsListView, basename='docs-api')
router.register(r'doc-type', docs.DocTypeView, basename='doc-type-api')

# Tender
router.register(r'tender', tender.TenderListView, basename='tender-api')
router.register(r'tender-notices', tender.TenderNoticesView, basename='tender-not-api')

# Quizz
router.register(r'quizz', quizz.QuizzListView, basename='quizz-api')

# Typo
router.register(r'typo', typo.TypoView, basename='typo-api')

# Contact
router.register(r'contact', contact.ContactView, basename='contact-api')
router.register(r'feedback', contact.FeedbackView, basename='feedback-api')
# router.register(r'get_stats', contact.GetStatsView, basename='get-feedback-api')
router.register(r'reception', contact.ReceptionView, basename='reception-api')
router.register(r'appeal', contact.AppealView, basename='appeal-api')
router.register(r'car-info', about.CarInfoView, basename='car_info-api')

# Region
router.register(r'regions', site.RegionView, basename='region-api')
router.register(r'districts', site.DistrictView, basename='district-api')
router.register(r'employee-rating', service.EmployeeRatingModalViewSet, basename='employee_rating-api')
router.register(r'regiondepartment', site.RegionDepartmentView, basename='regiondepartment-api')

# Rating API
rating_router = routers.DefaultRouter()
rating_router.register(r'rating-filter', service.EmployeeRatingModalViewSet, basename='rating-filter-api')
rating_router.register(r'rating-department_grade', service.EmployeeRatingModalViewSet,
                       basename='rating-department_grade-api')
rating_router.register(r'rating-structura_department', service.EmployeeRatingModalViewSet,
                       basename='rating-structura_department-api')

# Vote API
vote_router = routers.DefaultRouter()
vote_router.register(r'participants', rating.ParticipantsViewSet, basename='vote-participants-api')
vote_router.register(r'evolution_criteria', rating.EvolutionCriteriaViewSet, basename='vote-evolution_criteria-api')
vote_router.register(r'participants_vote', rating.VoteViewSet, basename='vote-participants_vote-api')
vote_router.register(r'participants_filter', rating.ParticipantsFilterViewSet, basename='vote-participants_filter-api')
vote_router.register(r'bot_link', rating.BotLinkViewSet, basename='vote-bot_link-api')
vote_router.register(r'department', about.DepartmentView, basename='vote-department-api')
vote_router.register(r'organizations', about.OrganizationView, basename='vote-organization-api')
vote_router.register(r'regions', site.RegionView, basename='vote-region-api')
vote_router.register(r'districts', site.DistrictView, basename='vote-district-api')

# Admin panel API
adm_router = routers.DefaultRouter()
adm_router.register(r'users', auth.UserView, basename='adm-users-api')
adm_router.register(r'role', auth.GroupView, basename='adm-role-api')
adm_router.register(r'permission', auth.PermissionView, basename='adm-permission-api')
adm_router.register(r'about', about.AdmAboutMinistryView, basename='adm-about-api')
adm_router.register(r'structure', about.AdmMinistryStructureView, basename='adm-structure-api')
adm_router.register(r'staff', about.AdmMinistryStaffView, basename='adm-staff-api')
adm_router.register(r'stat', about.AdmMinistryStatView, basename='adm-stat-api')
adm_router.register(r'department', about.AdmMinistryDepartmentView, basename='adm-department-api')
adm_router.register(r'organization', about.AdmMinistryOrganizationView, basename='adm-organization-api')
adm_router.register(r'organization_type', about.AdmOrganizationTypeView, basename='adm-organization_type-api')
adm_router.register(r'index', index.IndexView, basename='adm-index-api')
adm_router.register(r'vacancy', vacancy.AdmVacancyView, basename='adm-vacancy-api')
adm_router.register(r'education', vacancy.AdmEducationView, basename='adm-education-api')
adm_router.register(r'employment', vacancy.AdmEmploymentView, basename='adm-employment-api')
adm_router.register(r'service', service.AdmServiceView, basename='adm-service-api')
adm_router.register(r'doc_type', docs.AdmDocTypeView, basename='adm-doc_type-api')
adm_router.register(r'docs', docs.AdmDocsView, basename='adm-docs-api')
adm_router.register(r'stadion', sport.AdmStadionView, basename='adm-station-api')
adm_router.register(r'sport_type', sport.AdmSportTypeView, basename='adm-sport_type-api')
adm_router.register(r'champion', sport.AdmChampionView, basename='adm-champion-api')
adm_router.register(r'news', news.AdmNewsView, basename='adm-news-api')
adm_router.register(r'news_media', news.AdmNewsSMediaView, basename='adm-news_media-api')
adm_router.register(r'news_image', news.AdmMediaImageView, basename='adm-news_image-api')
adm_router.register(r'news_hashtag', news.AdmNewsHashtagView, basename='adm-news_hashtag-api')
adm_router.register(r'news_category', news.AdmNewsCategoryView, basename='adm-news_category-api')
adm_router.register(r'photo_gallery', news.AdmPhotoGalleryView, basename='adm-photo_gallery-api')
adm_router.register(r'photo_gallery_image', news.AdmPhotoGalleryImageView, basename='adm-photo_gallery_image-api')
adm_router.register(r'video_gallery', news.AdmVideoGalleryView, basename='adm-video_gallery-api')
adm_router.register(r'press', news.AdmPressView, basename='adm-press-api')
adm_router.register(r'press_article', news.AdmPressArticleLinkView, basename='adm-press_article-api')
adm_router.register(r'faq', news.AdmFAQView, basename='adm-faq-api')
adm_router.register(r'external_image', gallery.AdmExternalImageView, basename='adm-external_image-api')
adm_router.register(r'event', event.AdmEventView, basename='adm-event-api')
adm_router.register(r'tender', tender.AdmTenderView, basename='adm-tender-api')
adm_router.register(r'tender-type', tender.AdmTenderTypeView, basename='adm-tender-type-api')
adm_router.register(r'tender-notices', tender.AdmTenderNoticesView, basename='adm-tender-notices-api')
adm_router.register(r'tender-photos', tender.AdmTenderNoticesPhotosView, basename='adm-tender-notices-photos-api')
adm_router.register(r'regions', site.AdmRegionView, basename='adm-region-api')
adm_router.register(r'districts', site.AdmDistrictView, basename='adm-district-api')
adm_router.register(r'quizz', quizz.AdmQuizzView, basename='adm-quizz-api')
adm_router.register(r'question', quizz.AdmQuestionView, basename='adm-question-api')
adm_router.register(r'link', site.AdmUsefulLinkView, basename='adm-link-api')
adm_router.register(r'quizz-result', quizz.AdmQuestionResultView, basename='adm-quizz-result-api')
adm_router.register(r'main-page', site.AdmMainPageSettingView, basename='adm-main-page-api')
adm_router.register(r'contact', site.AdmContactSettingView, basename='adm-contact-api')
adm_router.register(r'typo', site.AdmTypoView, basename='adm-typo-api')
adm_router.register(r'week-day', contact.AdmWeekDayView, basename='adm-week_day-api')
adm_router.register(f'reception', contact.AdmReceptionView, basename='adm-reception-api')
adm_router.register(r'menu', menu.AdmMenuView, basename='adm-menu-api')
adm_router.register(r'static-page', menu.AdmStaticPageView, basename='adm-static_page-api')

src/admin_panel/app/user/forms.py
from django import forms

from admin_panel.model import user, territorial


# class CreateCustomUserForm(forms.ModelForm):
#
#     username = forms.CharField(widget=forms.TextInput(), required=True)
#     phone = forms.CharField(widget=forms.NumberInput(), required=True)
#     password = forms.CharField(widget=forms.PasswordInput(), required=True, min_length=8)
#     email = forms.CharField(widget=forms.EmailInput(), required=False)
#     image = forms.ImageField(widget=forms.FileInput(), required=False)
#     is_superuser = forms.BooleanField(required=False)
#     region = forms.ModelChoiceField(queryset=territorial.Region.objects.all(), required=True)
#
#
#     class Meta:
#         model = user.CustomUser
#         fields = [
#             'user',
#             'phone',
#             'region',
#             'email',
#             'image',
#             'username',
#             'password',
#             'is_superuser',
#         ]

class CreateCustomUserForm(forms.ModelForm):
    class Meta:
        model = user.CustomUser
        fields = '__all__'

src/admin_panel/app/user/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from rolepermissions.mixins import HasRoleMixin

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import UpdateView

from .forms import CreateCustomUserForm
from django.contrib import messages
from django.views import generic
from admin_panel.app import views as custom
from admin_panel.model.user import CustomUser
from ...model.territorial import Region
# from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _


class CreateCustomUserView(HasRoleMixin, generic.CreateView):
    allowed_roles = 'admin'
    redirect_to_login = 'login'
    model = CustomUser
    template_name = 'back/user/user_create.html'
    form_class = CreateCustomUserForm
    success_url = reverse_lazy('user:user-list')

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()
        del data['csrfmiddlewaretoken']
        username = data['username']
        password = data['password']
        if User.objects.filter(username=username).exists():
            messages.success(request, _("Bunday foydalanuvchi avval ro'yxatdan o'tgan"))
            return HttpResponseRedirect(reverse_lazy('user:user-create'))

        region = Region.objects.get(id=int(data['region']))

        if data.get('is_superuser') == 'on':
            is_superuser = True
            is_staff = False
        else:
            is_superuser = False
            is_staff = True

        data['region'] = Region.objects.get(id=int(data['region']))

        user = User.objects.create(username=username, password=password, is_active=True, is_staff=is_staff,
                                   is_superuser=is_superuser)
        user.set_password(password)
        user.save()

        obj = self.model.objects.create(user=user, email=data['email'], phone=data['phone'], region=region)

        image = request.FILES.get('image')
        if image:
            obj.image = image

        # if is_superuser:
        #     assign_role(user, 'admin')
        # else:
        #     assign_role(user, 'staff')

        obj.save()
        return HttpResponseRedirect(self.success_url)


class UpdateCustomUserView(HasRoleMixin, UpdateView):
    allowed_roles = 'admin'
    redirect_to_login = 'login'
    template_name = 'back/user/user_update.html'
    form_class = CreateCustomUserForm
    model = CustomUser
    context_object_name = 'object'
    success_url = reverse_lazy('user:user-list')

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()
        del data['csrfmiddlewaretoken']
        print(data, 'data')
        username = data['username']
        password = data['password']

        if data.get('is_superuser') == 'on':
            is_superuser = True
            is_staff = False
        else:
            is_superuser = False
            is_staff = True

        region = Region.objects.get(id=int(data['region']))

        data['region'] = Region.objects.get(id=int(data['region']))

        # obj = self.model.objects.create(user=user, email=data['email'], phone=data['phone'], region=region)
        obj = self.model.objects.get(id=self.kwargs['pk'])
        if User.objects.filter(username=username).exists():
            messages.success(request, _("Bunday foydalanuvchi avval ro'yxatdan o'tgan"))
            return HttpResponseRedirect(reverse_lazy('user:user-update', kwargs={'pk': obj.id}))

        obj.user.username = username
        obj.user.is_superuser = is_superuser
        obj.user.is_staff = is_staff
        obj.user.set_password(password)
        obj.user.save()

        obj.email = data['email']
        obj.phone = data['phone']
        obj.region = region

        image = request.FILES.get('image')
        if image:
            obj.image = image

        obj.save()
        return HttpResponseRedirect(self.success_url)


# class CustomUserList(views.SuperuserRequiredMixin, custom.CustomListView):
class CustomUserList(HasRoleMixin, custom.CustomListView):
    allowed_roles = 'admin'
    redirect_to_login = 'login'
    model = CustomUser
    queryset = model.objects.filter(user__is_superuser=False)
    template_name = 'back/user/user_list.html'
    permission_required = 'auth.user.manage'


class CustomUserDelete(HasRoleMixin, custom.CustomDeleteView):
    allowed_roles = 'admin'
    redirect_to_login = 'login'
    model = CustomUser
    success_url = reverse_lazy('user:user-list')

src/templates/back/user/user_list.html
{% extends 'back/_base.html' %}
{% load i18n %}
{% block mainbread %}
    <ul class="nav navbar-nav bookmark-icons">
        <div class="d-flex main-bread">
            <h5 class="content-header-title float-left pr-1 mb-0">{% trans 'Foydalanuvchilar' %}</h5>
            <div class="breadcrumb-wrapper">
                <ol class="breadcrumb p-0 mb-0">
                    <li class="breadcrumb-item"><a href="{% url 'index-admin' %}"><i class="bx bx-home-alt"></i></a>
                    </li>
                    <li class="breadcrumb-item active"><a href="#">{% trans 'Barcha foydalanuvchilar' %}</a>
                    </li>
                </ol>
            </div>
        </div>
    </ul>
{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'back/app-assets/css/main-list.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/extensions/dataTables.checkboxes.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/responsive.bootstrap.min.css' %}">
{% endblock %}

{% block body %}
    {% include 'back/parts/menu.html' %}
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="heading-elements">
                                <ul class="list-inline mb-0 main-list-heading">
                                    <li class="add-new-button"><a class="btn btn-primary"
                                                                  href="{% url 'user:user-create' %}"><i
                                            class="bx bxs-plus-square mr-1"></i>{% trans 'Yangi qo‘shish' %}</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- table Transactions start -->
                <section id="table-transactions">
                    <div class="card">
                        <!-- datatable start -->
                        <div class="table-responsive">
                            <table id="table-extended-transactions" class="table mb-0">
                                <thead>
                                <tr>
                                    <th class="pr-2">№</th>
                                    <th class="pl-0 post-title">{% trans 'username' %}</th>
                                    <th>{% trans 'sanasi' %}</th>
                                    <th class="text-center">{% trans 'hudud' %}</th>
                                    <th class="text-center">{% trans 'telefon' %}</th>
                                    <th>{% trans 'admin' %}</th>
                                    <th class="text-right">{% trans 'amallar' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in objects %}
                                    <tr>
                                        <td class="pr-2">{{ forloop.counter0 | add:objects.start_index }}</td>

                                        <td class="pl-0 post-title"><a href="{% url 'user:user-update' object.id %}">
                                            {{ object.user.username | truncatechars:"150" }}</a></td>
                                        <td>{{ object.created_at }}</td>
                                        <td class="text-center">
                                            {{ object.region.title }}
                                        </td>
                                        <td class="text-center">{{ object.phone }}</td>
                                        <td>admin/staff</td>
                                        <td class="text-right amallar">
                                            <div class="dropdown">
                                                <span class="bx bx-dots-vertical-rounded font-medium-3 dropdown-toggle nav-hide-arrow cursor-pointer"
                                                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                                      role="menu"></span>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item"
                                                       href="{% url 'user:user-update' object.id %}"><i
                                                            class="bx bx-edit-alt mr-1"></i> {% trans 'tahrirlash' %}</a>
                                                    <a class="dropdown-item removeButton" data-id="{{ object.id }}"
                                                       href="{% url 'user:user-delete' object.id %}"><i
                                                            class="bx bx-trash mr-1"></i>
                                                        {% trans 'o‘chirish' %}</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if objects.has_other_pages %}

                                <nav aria-label="Page navigation example">
                                    <ul class="pagination mt-2 ml-2">
                                        {% if objects.has_previous %}
                                            <li class="page-item previous"><a class="page-link"
                                                                              href="?page={{ objects.previous_page_number }}">
                                                <i class="bx bx-chevron-left"></i>
                                            </a></li>
                                        {% else %}

                                            <li class="page-item previous disabled"><a class="page-link" href="">
                                                <i class="bx bx-chevron-left"></i>
                                            </a></li>
                                        {% endif %}
                                        {% for n in objects.paginator.page_range %}
                                            {% if objects.number == n %}
                                                <li class="page-item active" aria-current="page"><a class="page-link"
                                                                                                    href="#">{{ n }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item"><a class="page-link"
                                                                         href="?page={{ n }}">{{ n }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if objects.has_next %}

                                            <li class="page-item next"><a class="page-link"
                                                                          href="?page={{ objects.next_page_number }}">
                                                <i class="bx bx-chevron-right"></i>
                                            </a></li>
                                        {% else %}
                                            <li class="page-item next disabled"><a class="page-link" href="#">
                                                <i class="bx bx-chevron-right"></i>
                                            </a></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            {% endif %}
                        </div>
                        <!-- datatable ends -->
                    </div>
                </section>
                <!-- table Transactions end -->
            </div>
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
{% endblock %}

{% block js %}
    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/datatables.checkboxes.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/responsive.bootstrap.min.js' %}"></script>
    <!-- END: Page Vendor JS-->
    <!-- BEGIN: Page JS-->
    <script src="{% static 'back/app-assets/js/scripts/pages/app-invoice.js' %}"></script>
    <!-- END: Page JS-->
{% endblock %}