src/admin_panel/app/link/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'link'

urlpatterns = [
    path('', login_required(views.LinkList.as_view()), name='link-list'),
    path('create/', login_required(views.LinkCreate.as_view()), name='link-create'),
    path('update/<int:pk>/', login_required(views.LinkUpdate.as_view()), name='link-update'),
    path('delete/<int:pk>/', login_required(views.LinkDelete.as_view()), name='link-delete'),
]

src/admin_panel/app/news/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from . import views

app_name = 'news'

urlpatterns = [
    path('', login_required(views.NewsList.as_view()), name='news-list'),
    path('create/', login_required(views.NewsCreate.as_view()), name='news-create'),

    path('media/<int:pk>/', login_required(views.NewsMedia.as_view()), name='news-media'),

    path('update/<int:pk>/', login_required(views.NewsUpdate.as_view()), name='news-update'),
    path('delete/<int:pk>/', login_required(views.NewsDelete.as_view()), name='news-delete'),

    path('category/', login_required(views.NewsCategoryList.as_view()), name='category-list'),
    path('category/create/', login_required(views.NewsCategoryCreate.as_view()), name='category-create'),
    path('category/update/<int:pk>/', login_required(views.NewsCategoryUpdate.as_view()), name='category-update'),
    path('category/delete/<int:pk>/', login_required(views.NewsCategoryDelete.as_view()), name='category-delete'),

    path('hashtag/', login_required(views.NewsHashtagList.as_view()), name='hashtag-list'),
    path('hashtag/create/', login_required(views.NewsHashtagCreate.as_view()), name='hashtag-create'),
    path('hashtag/update/<int:pk>/', login_required(views.NewsHashtagUpdate.as_view()), name='hashtag-update'),
    path('hashtag/delete/<int:pk>/', login_required(views.NewsHashtagDelete.as_view()), name='hashtag-delete'),


    path('faq/', login_required(views.FAQList.as_view()), name='faq-list'),
    path('faq/create/', login_required(views.FAQCreate.as_view()), name='faq-create'),
    path('faq/update/<int:pk>/', login_required(views.FAQUpdate.as_view()), name='faq-update'),
    path('faq/delete/<int:pk>/', login_required(views.FAQDelete.as_view()), name='faq-delete'),

    path('press/', login_required(views.PressList.as_view()), name='press-list'),
    path('press/create/', login_required(views.PressCreate.as_view()), name='press-create'),
    path('press/update/<int:pk>/', login_required(views.PressUpdate.as_view()), name='press-update'),
    path('press/delete/<int:pk>/', login_required(views.PressDelete.as_view()), name='press-delete'),


    path('article/', login_required(views.ArticleList.as_view()), name='article-list'),
    path('article/create/', login_required(views.ArticleCreate.as_view()), name='article-create'),
    path('article/update/<int:pk>/', login_required(views.ArticleUpdate.as_view()), name='article-update'),
    path('article/delete/<int:pk>/', login_required(views.ArticleDelete.as_view()), name='article-delete'),


]

src/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api import search

router = routers.DefaultRouter()
# Importing models
from api.about import views as about
from api.settings import views as site
from api.news import views as news
from api.gallery import views as gallery
from api.event import views as event
from api.sport import views as sport
from api.docs import views as docs
from api.tender import views as tender
from api.service import views as service
from api.quizz import views as quizz
from api.contact import views as contact
from api.search import views as search
from api.static import views as static
from api.typo import views as typo
from api.rating import views as rating
from api.auth import views as auth
from api.index import views as index
from api.vacancy import views as vacancy
from api.menu import views as menu

# Settings
router.register(r'site-contact', site.SiteContactView, basename='site-contact-api')

# Index
router.register(r'header', site.HeaderView, basename='header-api')
router.register(r'footer', site.FooterView, basename='footer-api')
router.register(r'top-news', news.IndexNewsListView, basename='top-news-api')
router.register(r'top-news-medium', news.IndexNewsLongListView, basename='top-news-medium-api')
router.register(r'service', service.ServiceListView, basename='service-api')
router.register(r'contact-stat', contact.IndexContactView, basename='contact-stat-api')
router.register(r'top-event', event.IndexEventListView, basename='top-event-api')
router.register(r'top-gallery', gallery.IndexPhotoListView, basename='top-gallery-api')
router.register(r'poster', site.PosterView, basename='poster-api')
router.register(r'top-quizz', quizz.QuizzView, basename='top-quiz-api')
router.register(r'link', site.UsefulLinkView, basename='link-api')

# About us page
router.register(r'about', about.AboutUsView, basename='about-api')
router.register(r'number_data_from_erp', about.IntegrationErpNumberDataView, basename='number_data_from_erp-api')

router.register(r'staff-list', about.StaffListView, basename='filter-staff-api')
router.register(r'structure', about.StructureView, basename='structure-api')
router.register(r'visitor', about.VisitorView, basename='visitor-api')

# Department & Organization
router.register(r'all-department', about.AllDepartmentView, basename='all-department-api')
router.register(r'department', about.DepartmentView, basename='department-api')
router.register(r'organizations', about.OrganizationView, basename='organization-api')
router.register(r'organization_type', about.OrganizationTypeView, basename='organization_type-api')

# Vacancy
router.register(r'vacancy', about.VacancyView, basename='vacancy-api')

# All staff and leaders
router.register(r'leader', about.StaffView, basename='leader-api')
router.register(r'leader-region', about.StaffRegionView, basename='leader-region-api')
router.register(r'leader-organization', about.StaffOrganizationView, basename='leader-organization-api')
router.register(r'leader-central', about.StaffCentralView, basename='leader-central-api')

# Press API
router.register(r'news', news.NewsListView, basename='news-api')
router.register(r'news-integration', news.NewsIntegration, basename='news-api-integration')
router.register(r'news-region', news.NewsRegionView, basename='news-region-api')
router.register(r'news-header', news.HeaderNewsListView, basename='news-header-api')
router.register(r'news-category', news.NewsCategoryView, basename='news-category-api')
router.register(r'news-hashtag', news.NewsHashtagView, basename='news-hashtag-api')
router.register(r'main-news', news.MainNewsListView, basename='main-api')
router.register(r'press', news.PressListView, basename='press-api')
router.register(r'faq', news.FAQListView, basename='faq-api')

# Static page
router.register(r'static', static.StaticView, basename='static-api')
router.register(r'static_data', static.StaticDataView, basename='static_data-api')

# Gallery
router.register(r'photo', gallery.PhotoListView, basename='photo-api')
router.register(r'video', gallery.VideoListView, basename='video-api')

# Event
router.register(r'event', event.EventListView, basename='event-api')

# Sport
router.register(r'stadion', sport.StadionListView, basename='sport-api')
router.register(r'champion', sport.ChampionView, basename='champion-api')
router.register(r'champion-list', sport.ChampionListView, basename='champion-list-api')

# Docs
router.register(r'docs', docs.DocsListView, basename='docs-api')
router.register(r'doc-type', docs.DocTypeView, basename='doc-type-api')

# Tender
router.register(r'tender', tender.TenderListView, basename='tender-api')
router.register(r'tender-notices', tender.TenderNoticesView, basename='tender-not-api')

# Quizz
router.register(r'quizz', quizz.QuizzListView, basename='quizz-api')

# Typo
router.register(r'typo', typo.TypoView, basename='typo-api')

# Contact
router.register(r'contact', contact.ContactView, basename='contact-api')
router.register(r'feedback', contact.FeedbackView, basename='feedback-api')
# router.register(r'get_stats', contact.GetStatsView, basename='get-feedback-api')
router.register(r'reception', contact.ReceptionView, basename='reception-api')
router.register(r'appeal', contact.AppealView, basename='appeal-api')
router.register(r'car-info', about.CarInfoView, basename='car_info-api')

# Region
router.register(r'regions', site.RegionView, basename='region-api')
router.register(r'districts', site.DistrictView, basename='district-api')
router.register(r'employee-rating', service.EmployeeRatingModalViewSet, basename='employee_rating-api')
router.register(r'regiondepartment', site.RegionDepartmentView, basename='regiondepartment-api')

# Rating API
rating_router = routers.DefaultRouter()
rating_router.register(r'rating-filter', service.EmployeeRatingModalViewSet, basename='rating-filter-api')
rating_router.register(r'rating-department_grade', service.EmployeeRatingModalViewSet,
                       basename='rating-department_grade-api')
rating_router.register(r'rating-structura_department', service.EmployeeRatingModalViewSet,
                       basename='rating-structura_department-api')

# Vote API
vote_router = routers.DefaultRouter()
vote_router.register(r'participants', rating.ParticipantsViewSet, basename='vote-participants-api')
vote_router.register(r'evolution_criteria', rating.EvolutionCriteriaViewSet, basename='vote-evolution_criteria-api')
vote_router.register(r'participants_vote', rating.VoteViewSet, basename='vote-participants_vote-api')
vote_router.register(r'participants_filter', rating.ParticipantsFilterViewSet, basename='vote-participants_filter-api')
vote_router.register(r'bot_link', rating.BotLinkViewSet, basename='vote-bot_link-api')
vote_router.register(r'department', about.DepartmentView, basename='vote-department-api')
vote_router.register(r'organizations', about.OrganizationView, basename='vote-organization-api')
vote_router.register(r'regions', site.RegionView, basename='vote-region-api')
vote_router.register(r'districts', site.DistrictView, basename='vote-district-api')

# Admin panel API
adm_router = routers.DefaultRouter()
adm_router.register(r'users', auth.UserView, basename='adm-users-api')
adm_router.register(r'role', auth.GroupView, basename='adm-role-api')
adm_router.register(r'permission', auth.PermissionView, basename='adm-permission-api')
adm_router.register(r'about', about.AdmAboutMinistryView, basename='adm-about-api')
adm_router.register(r'structure', about.AdmMinistryStructureView, basename='adm-structure-api')
adm_router.register(r'staff', about.AdmMinistryStaffView, basename='adm-staff-api')
adm_router.register(r'stat', about.AdmMinistryStatView, basename='adm-stat-api')
adm_router.register(r'department', about.AdmMinistryDepartmentView, basename='adm-department-api')
adm_router.register(r'organization', about.AdmMinistryOrganizationView, basename='adm-organization-api')
adm_router.register(r'organization_type', about.AdmOrganizationTypeView, basename='adm-organization_type-api')
adm_router.register(r'index', index.IndexView, basename='adm-index-api')
adm_router.register(r'vacancy', vacancy.AdmVacancyView, basename='adm-vacancy-api')
adm_router.register(r'education', vacancy.AdmEducationView, basename='adm-education-api')
adm_router.register(r'employment', vacancy.AdmEmploymentView, basename='adm-employment-api')
adm_router.register(r'service', service.AdmServiceView, basename='adm-service-api')
adm_router.register(r'doc_type', docs.AdmDocTypeView, basename='adm-doc_type-api')
adm_router.register(r'docs', docs.AdmDocsView, basename='adm-docs-api')
adm_router.register(r'stadion', sport.AdmStadionView, basename='adm-station-api')
adm_router.register(r'sport_type', sport.AdmSportTypeView, basename='adm-sport_type-api')
adm_router.register(r'champion', sport.AdmChampionView, basename='adm-champion-api')
adm_router.register(r'news', news.AdmNewsView, basename='adm-news-api')
adm_router.register(r'news_media', news.AdmNewsSMediaView, basename='adm-news_media-api')
adm_router.register(r'news_image', news.AdmMediaImageView, basename='adm-news_image-api')
adm_router.register(r'news_hashtag', news.AdmNewsHashtagView, basename='adm-news_hashtag-api')
adm_router.register(r'news_category', news.AdmNewsCategoryView, basename='adm-news_category-api')
adm_router.register(r'photo_gallery', news.AdmPhotoGalleryView, basename='adm-photo_gallery-api')
adm_router.register(r'photo_gallery_image', news.AdmPhotoGalleryImageView, basename='adm-photo_gallery_image-api')
adm_router.register(r'video_gallery', news.AdmVideoGalleryView, basename='adm-video_gallery-api')
adm_router.register(r'press', news.AdmPressView, basename='adm-press-api')
adm_router.register(r'press_article', news.AdmPressArticleLinkView, basename='adm-press_article-api')
adm_router.register(r'faq', news.AdmFAQView, basename='adm-faq-api')

src/templates/back/press_service/press/article_list.html
{% extends 'back/_base.html' %}
{% load i18n %}
{% block mainbread %}
    <ul class="nav navbar-nav bookmark-icons">
        <div class="d-flex main-bread">
            <h5 class="content-header-title float-left pr-1 mb-0">{% trans 'OAV maqolalari' %}</h5>
            <div class="breadcrumb-wrapper">
                <ol class="breadcrumb p-0 mb-0">
                    <li class="breadcrumb-item"><a href="{% url 'index-admin' %}"><i class="bx bx-home-alt"></i></a>
                    </li>
                    <li class="breadcrumb-item active"><a href="#">{% trans 'Barcha maqolalar' %}</a>
                    </li>
                </ol>
            </div>
        </div>
    </ul>
{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'back/app-assets/css/main-list.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/extensions/dataTables.checkboxes.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/responsive.bootstrap.min.css' %}">
{% endblock %}

{% block body %}
    {% include 'back/parts/menu.html' %}
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="heading-elements">
                                <ul class="list-inline mb-0 main-list-heading">
                                    <li class="add-new-button"><a class="btn btn-primary"
                                                                  href="{% url 'news:article-create' %}"><i
                                            class="bx bxs-plus-square mr-1"></i>{% trans 'Yangi qo‘shish' %}</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- table Transactions start -->
                <section id="table-transactions">
                    <div class="card">
                        <!-- datatable start -->
                        <div class="table-responsive">
                            <table id="table-extended-transactions" class="table mb-0">
                                <thead>
                                <tr>
                                    <th class="pr-0">№</th>
                                    <th class="pl-0">{% trans 'nomi' %}</th>
                                    <th class="text-center">{% trans 'til' %}</th>
                                    <th class="text-right">{% trans 'link' %}</th>
                                    <th class="text-right">{% trans 'amallar' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for object in objects %}
                                    <tr>
                                        <td class="pr-2">{{ forloop.counter0 | add:objects.start_index }}</td>
                                        <td class="pl-0"><a href="{% url 'news:article-update' object.id %}">
                                            {{ object.title | truncatechars:"150" }}</a></td>
                                        <td class="text-center">
                                            {{ object.language }}
                                        </td>
                                        <td class="text-right">
                                            {{ object.link }}
                                        </td>
                                        <td class="text-right amallar">
                                            <div class="dropdown">
                                                <span class="bx bx-dots-vertical-rounded font-medium-3 dropdown-toggle nav-hide-arrow cursor-pointer"
                                                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                                      role="menu"></span>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item"
                                                       href="{% url 'news:article-update' object.id %}"><i
                                                            class="bx bx-edit-alt mr-1"></i>{% trans 'tahrirlash' %}</a>
                                                    <a class="dropdown-item removeButton" data-id="{{ object.id }}"
                                                       href="{% url 'news:article-delete' object.id %}"><i
                                                            class="bx bx-trash mr-1"></i>
                                                        {% trans 'o‘chirish' %}</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            {% if objects.has_other_pages %}

                                <nav aria-label="Page navigation example">
                                    <ul class="pagination mt-2 ml-2">
                                        {% if objects.has_previous %}
                                            <li class="page-item previous"><a class="page-link"
                                                                              href="?page={{ objects.previous_page_number }}">
                                                <i class="bx bx-chevron-left"></i>
                                            </a></li>
                                        {% else %}

                                            <li class="page-item previous disabled"><a class="page-link" href="">
                                                <i class="bx bx-chevron-left"></i>
                                            </a></li>
                                        {% endif %}
                                        {% for n in objects.paginator.page_range %}
                                            {% if objects.number == n %}
                                                <li class="page-item active" aria-current="page"><a class="page-link"
                                                                                                    href="#">{{ n }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item"><a class="page-link"
                                                                         href="?page={{ n }}">{{ n }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if objects.has_next %}

                                            <li class="page-item next"><a class="page-link"
                                                                          href="?page={{ objects.next_page_number }}">
                                                <i class="bx bx-chevron-right"></i>
                                            </a></li>
                                        {% else %}
                                            <li class="page-item next disabled"><a class="page-link" href="#">
                                                <i class="bx bx-chevron-right"></i>
                                            </a></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            {% endif %}
                        </div>
                        <!-- datatable ends -->
                    </div>
                </section>
                <!-- table Transactions end -->
            </div>
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
{% endblock %}

{% block js %}
    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/datatables.checkboxes.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/responsive.bootstrap.min.js' %}"></script>
    <!-- END: Page Vendor JS-->
    <!-- BEGIN: Page JS-->
    <script src="{% static 'back/app-assets/js/scripts/pages/app-invoice.js' %}"></script>
    <!-- END: Page JS-->
{% endblock %}

src/templates/back/press_service/press/press_update.html
{% extends 'back/_base.html' %}
{% load static i18n %}
{% block mainbread %}
    <ul class="nav navbar-nav bookmark-icons">
        <div class="d-flex main-bread">
            <h5 class="content-header-title float-left pr-1 mb-0">{% trans 'Manbaa' %}</h5>
            <div class="breadcrumb-wrapper">
                <ol class="breadcrumb p-0 mb-0">
                    <li class="breadcrumb-item"><a href="{% url 'index-admin' %}"><i class="bx bx-home-alt"></i></a>
                    </li>
                    <li class="breadcrumb-item"><a href="{% url 'link:link-list' %}">{% trans 'Barcha manbaalar' %}</a>
                    </li>
                    <li class="breadcrumb-item active">{% trans 'Manbani tahrirlash' %}
                    </li>
                </ol>
            </div>
        </div>
    </ul>
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'back/app-assets/vendors/css/vue-ctk-date-time-picker.css' %}">
    <link rel="stylesheet" href="{% static 'back/app-assets/vendors/css/vue2-editor.css' %}">
    <link rel="stylesheet" href="{% static 'back/app-assets/vendors/css/katex.min.css' %}">
    <link rel="stylesheet" href="{% static 'back/app-assets/vendors/css/monokai-sublime.min.css' %}">
    <link rel="stylesheet" href="{% static 'back/app-assets/css/quill.snow.css' %}"/>
    <link rel="stylesheet" href="{% static 'back/app-assets/css/quill.imageUploader.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'back/app-assets/css/main-editor.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'back/app-assets/vendors/css/ui/prism.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/file-uploaders/dropzone.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/css/plugins/file-uploaders/dropzone.min.css' %}">
    <link rel="stylesheet" href="{% static 'back/app-assets/vendors/css/filepond.min.css' %}">
    <link rel="stylesheet" href="{% static 'back/app-assets/vendors/css/filepond-plugin-image-preview.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/forms/select/select2.min.css' %}">
{% endblock %}

{% block body %}
    {% include 'back/parts/menu.html' %}
    <!-- BEGIN: Content-->
    <div class="app-content content" id="app">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <!-- app invoice View Page -->
                <form action="{% url 'news:press-update' object.id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <section class="invoice-edit-wrapper">
                        <div class="row">
                            <!-- invoice view page -->
                            <div class="col-xl-8 col-md-8 col-12 mt-4">

                                <div class="card">

                                    <div class="card-header">
                                        <h4 class="card-title" style="text-transform: inherit;">{% trans 'Manba' %}</h4>
                                    </div>
                                    <div class="card-content">
                                                <div class="card-body pb-1 mx-25">
                                                    <div class="row invoice-info">
                                                        <div class="col-lg-12 col-md-12">
                                                            <fieldset class="invoice-address form-group">
                                                                <input type="text" v-model="title"
                                                                       class="form-control" required
                                                                       placeholder="{% trans 'Manba nomini kiriting' %}"
                                                                       name="title">
                                                            </fieldset>

                                                        </div>
                                                    </div>

                                                    <div class="row invoice-info">
                                                        <div class="col-lg-12 col-md-12">
                                                            <fieldset class="invoice-address form-group">
                                                                <input type="text" v-model="link"
                                                                       class="form-control" required
                                                                       placeholder="{% trans 'Manba linkini kiriting' %}"
                                                                       name="link">
                                                            </fieldset>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                </div>

                            </div>
                            <!-- invoice action  -->
                            <div class="col-xl-4 col-md-4 col-12 mt-4">
                                <div class="card invoice-action-wrapper shadow-none border">
                                    <div class="card-body">
                                        <div class="invoice-action-btn mb-1">
                                            <button type="submit" class="btn btn-primary btn-block invoice-send-btn">
                                                <i class="bx bxs-save"></i>
                                                <span>{% trans 'Saqlash' %}</span>
                                            </button>
                                        </div>
                                        <div class="invoice-action-btn mb-1">
                                            <div class="save">
                                                <a href="{% url 'news:press-list' %}" class="btn btn-light-danger btn-block">
                                                    <span class="text-nowrap">{% trans 'O‘chirish' %}</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-header">
                                        <h4 class="card-title">{% trans 'Belgi' %}</h4>
                                    </div>
                                    <div class="card-content">
                                        <div class="card-body">
                                            {% if object.icon %}
                                                <a href="{{ object.icon.url }}">{{ object.icon.name }}</a>
                                            {% endif %}

                                            <input type="file" name="icon">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                </form>
            </div>
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
{% endblock %}

{% block js %}
    <script src="{% static 'back/app-assets/vendors/js/filepond-plugin-image-preview.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/filepond.js' %}"></script>
    <script src="{% static 'back/app-assets/js/vue.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/vue-ctk-date-time-picker.umd.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/katex.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/highlight.min.js' %}"></script>
    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'back/app-assets/vendors/js/forms/select/select2.full.min.js' %}"></script>
    <!-- END: Page Vendor JS-->
    <script src="{% static 'back/app-assets/js/scripts/forms/select/form-select2.min.js' %}"></script>

    <script type="text/javascript">
        var app = new Vue({
            el: '#app',
            data: {
                title: '{{ object.title|escapejs }}',
                link: '{{ object.link|escapejs }}',

                message: 'Hello!',
                value: null,
                myFiles: null,
                videotrue: false
            },
        });
    </script>
{% endblock %}