src/admin_panel/app/typo/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

app_name = 'typo'

urlpatterns = [
    path('', login_required(views.TypoList.as_view()), name='typo-list'),
    # path('create/', login_required(views.TypoCreate.as_view()), name='typo-create'),
    path('update/<int:pk>/', login_required(views.TypoUpdate.as_view()), name='typo-update'),
    path('delete/<int:pk>/', login_required(views.TypoDelete.as_view()), name='typo-delete'),
]

src/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api import search

router = routers.DefaultRouter()
# Importing models
from api.about import views as about
from api.settings import views as site
from api.news import views as news
from api.gallery import views as gallery
from api.event import views as event
from api.sport import views as sport
from api.docs import views as docs
from api.tender import views as tender
from api.service import views as service
from api.quizz import views as quizz
from api.contact import views as contact
from api.search import views as search
from api.static import views as static
from api.typo import views as typo
from api.rating import views as rating
from api.auth import views as auth
from api.index import views as index
from api.vacancy import views as vacancy
from api.menu import views as menu

# Settings
router.register(r'site-contact', site.SiteContactView, basename='site-contact-api')

# Index
router.register(r'header', site.HeaderView, basename='header-api')
router.register(r'footer', site.FooterView, basename='footer-api')
router.register(r'top-news', news.IndexNewsListView, basename='top-news-api')
router.register(r'top-news-medium', news.IndexNewsLongListView, basename='top-news-medium-api')
router.register(r'service', service.ServiceListView, basename='service-api')
router.register(r'contact-stat', contact.IndexContactView, basename='contact-stat-api')
router.register(r'top-event', event.IndexEventListView, basename='top-event-api')
router.register(r'top-gallery', gallery.IndexPhotoListView, basename='top-gallery-api')
router.register(r'poster', site.PosterView, basename='poster-api')
router.register(r'top-quizz', quizz.QuizzView, basename='top-quiz-api')
router.register(r'link', site.UsefulLinkView, basename='link-api')

# About us page
router.register(r'about', about.AboutUsView, basename='about-api')
router.register(r'number_data_from_erp', about.IntegrationErpNumberDataView, basename='number_data_from_erp-api')

router.register(r'staff-list', about.StaffListView, basename='filter-staff-api')
router.register(r'structure', about.StructureView, basename='structure-api')
router.register(r'visitor', about.VisitorView, basename='visitor-api')

# Department & Organization
router.register(r'all-department', about.AllDepartmentView, basename='all-department-api')
router.register(r'department', about.DepartmentView, basename='department-api')
router.register(r'organizations', about.OrganizationView, basename='organization-api')
router.register(r'organization_type', about.OrganizationTypeView, basename='organization_type-api')

# Vacancy
router.register(r'vacancy', about.VacancyView, basename='vacancy-api')

# All staff and leaders
router.register(r'leader', about.StaffView, basename='leader-api')
router.register(r'leader-region', about.StaffRegionView, basename='leader-region-api')
router.register(r'leader-organization', about.StaffOrganizationView, basename='leader-organization-api')
router.register(r'leader-central', about.StaffCentralView, basename='leader-central-api')

# Press API
router.register(r'news', news.NewsListView, basename='news-api')
router.register(r'news-integration', news.NewsIntegration, basename='news-api-integration')
router.register(r'news-region', news.NewsRegionView, basename='news-region-api')
router.register(r'news-header', news.HeaderNewsListView, basename='news-header-api')
router.register(r'news-category', news.NewsCategoryView, basename='news-category-api')
router.register(r'news-hashtag', news.NewsHashtagView, basename='news-hashtag-api')
router.register(r'main-news', news.MainNewsListView, basename='main-api')
router.register(r'press', news.PressListView, basename='press-api')
router.register(r'faq', news.FAQListView, basename='faq-api')

# Static page
router.register(r'static', static.StaticView, basename='static-api')
router.register(r'static_data', static.StaticDataView, basename='static_data-api')

# Gallery
router.register(r'photo', gallery.PhotoListView, basename='photo-api')
router.register(r'video', gallery.VideoListView, basename='video-api')

# Event
router.register(r'event', event.EventListView, basename='event-api')

# Sport
router.register(r'stadion', sport.StadionListView, basename='sport-api')
router.register(r'champion', sport.ChampionView, basename='champion-api')
router.register(r'champion-list', sport.ChampionListView, basename='champion-list-api')

# Docs
router.register(r'docs', docs.DocsListView, basename='docs-api')
router.register(r'doc-type', docs.DocTypeView, basename='doc-type-api')

# Tender
router.register(r'tender', tender.TenderListView, basename='tender-api')
router.register(r'tender-notices', tender.TenderNoticesView, basename='tender-not-api')

# Quizz
router.register(r'quizz', quizz.QuizzListView, basename='quizz-api')

# Typo
router.register(r'typo', typo.TypoView, basename='typo-api')

# Contact
router.register(r'contact', contact.ContactView, basename='contact-api')
router.register(r'feedback', contact.FeedbackView, basename='feedback-api')
# router.register(r'get_stats', contact.GetStatsView, basename='get-feedback-api')
router.register(r'reception', contact.ReceptionView, basename='reception-api')
router.register(r'appeal', contact.AppealView, basename='appeal-api')
router.register(r'car-info', about.CarInfoView, basename='car_info-api')

# Region
router.register(r'regions', site.RegionView, basename='region-api')
router.register(r'districts', site.DistrictView, basename='district-api')
router.register(r'employee-rating', service.EmployeeRatingModalViewSet, basename='employee_rating-api')
router.register(r'regiondepartment', site.RegionDepartmentView, basename='regiondepartment-api')

# Rating API
rating_router = routers.DefaultRouter()
rating_router.register(r'rating-filter', service.EmployeeRatingModalViewSet, basename='rating-filter-api')
rating_router.register(r'rating-department_grade', service.EmployeeRatingModalViewSet,
                       basename='rating-department_grade-api')
rating_router.register(r'rating-structura_department', service.EmployeeRatingModalViewSet,
                       basename='rating-structura_department-api')

# Vote API
vote_router = routers.DefaultRouter()
vote_router.register(r'participants', rating.ParticipantsViewSet, basename='vote-participants-api')
vote_router.register(r'evolution_criteria', rating.EvolutionCriteriaViewSet, basename='vote-evolution_criteria-api')
vote_router.register(r'participants_vote', rating.VoteViewSet, basename='vote-participants_vote-api')
vote_router.register(r'participants_filter', rating.ParticipantsFilterViewSet, basename='vote-participants_filter-api')
vote_router.register(r'bot_link', rating.BotLinkViewSet, basename='vote-bot_link-api')
vote_router.register(r'department', about.DepartmentView, basename='vote-department-api')
vote_router.register(r'organizations', about.OrganizationView, basename='vote-organization-api')
vote_router.register(r'regions', site.RegionView, basename='vote-region-api')
vote_router.register(r'districts', site.DistrictView, basename='vote-district-api')

# Admin panel API
adm_router = routers.DefaultRouter()
adm_router.register(r'users', auth.UserView, basename='adm-users-api')
adm_router.register(r'role', auth.GroupView, basename='adm-role-api')
adm_router.register(r'permission', auth.PermissionView, basename='adm-permission-api')
adm_router.register(r'about', about.AdmAboutMinistryView, basename='adm-about-api')
adm_router.register(r'structure', about.AdmMinistryStructureView, basename='adm-structure-api')
adm_router.register(r'staff', about.AdmMinistryStaffView, basename='adm-staff-api')
adm_router.register(r'stat', about.AdmMinistryStatView, basename='adm-stat-api')
adm_router.register(r'department', about.AdmMinistryDepartmentView, basename='adm-department-api')
adm_router.register(r'organization', about.AdmMinistryOrganizationView, basename='adm-organization-api')
adm_router.register(r'organization_type', about.AdmOrganizationTypeView, basename='adm-organization_type-api')
adm_router.register(r'index', index.IndexView, basename='adm-index-api')
adm_router.register(r'vacancy', vacancy.AdmVacancyView, basename='adm-vacancy-api')
adm_router.register(r'education', vacancy.AdmEducationView, basename='adm-education-api')
adm_router.register(r'employment', vacancy.AdmEmploymentView, basename='adm-employment-api')
adm_router.register(r'service', service.AdmServiceView, basename='adm-service-api')
adm_router.register(r'doc_type', docs.AdmDocTypeView, basename='adm-doc_type-api')
adm_router.register(r'docs', docs.AdmDocsView, basename='adm-docs-api')
adm_router.register(r'stadion', sport.AdmStadionView, basename='adm-station-api')
adm_router.register(r'sport_type', sport.AdmSportTypeView, basename='adm-sport_type-api')
adm_router.register(r'champion', sport.AdmChampionView, basename='adm-champion-api')
adm_router.register(r'news', news.AdmNewsView, basename='adm-news-api')
adm_router.register(r'news_media', news.AdmNewsSMediaView, basename='adm-news_media-api')
adm_router.register(r'news_image', news.AdmMediaImageView, basename='adm-news_image-api')
adm_router.register(r'news_hashtag', news.AdmNewsHashtagView, basename='adm-news_hashtag-api')
adm_router.register(r'news_category', news.AdmNewsCategoryView, basename='adm-news_category-api')
adm_router.register(r'photo_gallery', news.AdmPhotoGalleryView, basename='adm-photo_gallery-api')
adm_router.register(r'photo_gallery_image', news.AdmPhotoGalleryImageView, basename='adm-photo_gallery_image-api')
adm_router.register(r'video_gallery', news.AdmVideoGalleryView, basename='adm-video_gallery-api')
adm_router.register(r'press', news.AdmPressView, basename='adm-press-api')
adm_router.register(r'press_article', news.AdmPressArticleLinkView, basename='adm-press_article-api')
adm_router.register(r'faq', news.AdmFAQView, basename='adm-faq-api')

src/admin_panel/app/typo/forms.py
from django.forms import ModelForm

from admin_panel.model.settings import Typo


class TypoForm(ModelForm):
    class Meta:
        model = Typo
        fields = '__all__'

src/admin_panel/app/typo/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from rolepermissions.mixins import HasRoleMixin

from admin_panel.app import views as custom
from admin_panel.model.settings import Typo
from django.views.generic import CreateView, UpdateView, ListView
from . import forms


# class TypoView(CreateView):
#     form_class = ErrorReportingForm
#
#     def get(self, request, *args, **kwargs):
#         return HttpResponseRedirect('/')
#
#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             form.save()
#             return JsonResponse({'status': 'OK'})
#         else:
#             return JsonResponse({'status': 'Error'})


class TypoUpdate(HasRoleMixin, UpdateView):
    allowed_roles = 'admin'
    redirect_to_login = 'login'
    model = Typo
    form_class = forms.TypoForm
    context_object_name = 'object'
    template_name = 'back/typo/typo_update.html'
    success_url = reverse_lazy('typo:typo-list')

    def post(self, request, *args, **kwargs):
        typo = self.model.objects.get(id=self.kwargs['pk'])

        corrected = request.POST.get('corrected')

        if corrected == 'on':
            corrected = True
        else:
            corrected = False

        typo.corrected = corrected
        typo.save()
        return HttpResponseRedirect(self.success_url)


class TypoList(HasRoleMixin, ListView):
    allowed_roles = 'admin'
    redirect_to_login = 'login'
    model = Typo
    template_name = 'back/typo/typo_list.html'
    queryset = model.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TypoList, self).get_context_data(object_list=object_list)
        objects = self.queryset

        q = self.request.GET.get('q')
        if q:
            objects = self.model.objects.filter(title__icontains=q)

        page = self.request.GET.get('page', 1)
        paginator = Paginator(objects, 12)

        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            objects = paginator.page(1)
        except EmptyPage:
            objects = paginator.page(paginator.num_pages)

        context['objects'] = objects
        return context


class TypoDelete(HasRoleMixin, custom.CustomDeleteView):
    allowed_roles = 'admin'
    redirect_to_login = 'login'
    model = Typo
    success_url = reverse_lazy('typo:typo-list')

src/api/typo/views.py
from rest_framework import viewsets, generics
from . import serializers


class TypoView(viewsets.ViewSet, generics.CreateAPIView):
    serializer_class = serializers.TypoSerializer
    pagination_class = None
    http_method_names = ['post']

src/templates/back/typo/typo_list.html
{% extends 'back/_base.html' %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block mainbread %}
    <ul class="nav navbar-nav bookmark-icons">
        <div class="d-flex main-bread">
            <h5 class="content-header-title float-left pr-1 mb-0">{% trans 'Saytdagi xatolar' %}</h5>
            <div class="breadcrumb-wrapper">
                <ol class="breadcrumb p-0 mb-0">
                    <li class="breadcrumb-item"><a href="{% url 'index-admin' %}"><i class="bx bx-home-alt"></i></a>
                    </li>
                    <li class="breadcrumb-item active"><a href="#">{% trans 'Barcha qayd etilganlar xatolar' %}</a>
                    </li>
                </ol>
            </div>
        </div>
    </ul>
{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'back/app-assets/css/main-list.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/extensions/dataTables.checkboxes.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'back/app-assets/vendors/css/tables/datatable/responsive.bootstrap.min.css' %}">
{% endblock %}

{% block body %}
    {% include 'back/parts/menu.html' %}
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="row breadcrumbs-top">
                        <div class="col-12">
                            <div class="heading-elements">
                                <ul class="list-inline mb-0 main-list-heading">
                                    <li class="main-searchh">
                                        {% if request.GET.q %}
                                            <fieldset class="position-relative">
                                                <form action="" method="GET">
                                                    <input type="text" name="q" class="form-control single-daterange"
                                                           placeholder="{% trans 'Izlash' %}" value="{{ request.GET.q }}"/>
                                                    <div class="form-control-position">
                                                        <a href="{% url 'typo:typo-list' %}"><i
                                                                class="bx bx-x font-medium-2"></i></a>
                                                    </div>
                                                </form>

                                            </fieldset>
                                        {% else %}
                                            <fieldset class="has-icon-left">
                                                <form action="" method="GET">
                                                    <input type="text" name="q" class="form-control single-daterange"
                                                           placeholder="{% trans 'Izlash' %}" value="{{ request.GET.q }}"/>
                                                    <div class="form-control-position">
                                                        <i class="bx bx-search font-medium-2"></i>
                                                    </div>
                                                </form>

                                            </fieldset>
                                        {% endif %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- table Transactions start -->
                <section id="table-transactions">
                    <div class="card">
                        <!-- datatable start -->
                        <div class="table-responsive">
                            <table id="table-extended-transactions" class="table mb-0">
                                <thead>
                                <tr>
                                    <th class="pr-2">№</th>
                                    <th class="pl-0">{% trans 'matn' %}</th>
                                    <th class="text-center">{% trans 'sahifa' %}</th>
                                    <th class="text-right">{% trans 'jo`natilgan sana' %}</th>
                                    <th class="text-right">{% trans 'amallar' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for typo in objects %}
                                    <tr>
                                        <td class="pr-2">{{ forloop.counter0 | add:objects.start_index }}</td>
                                        <td class="pl-0"><a href="{% url 'typo:typo-update' typo.id %}"><i
                                                class="bx bxs-circle {% if typo.corrected %}success{% else %}danger{% endif %} font-small-1 mr-50"></i>
                                            {{ typo.title|safe | truncatechars:"150" }}
                                        </a></td>
                                        <td class="text-center">{{ typo.page | truncatechars:"100" }}</td>
                                        <td class="text-right">{{ typo.created_at }}</td>
                                        <td class="text-right amallar">
                                            <div class="dropdown ">
                                            <span class="bx bx-dots-vertical-rounded font-medium-3 dropdown-toggle nav-hide-arrow cursor-pointer"
                                                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                                  role="menu"></span>
                                                <div class="dropdown-menu dropdown-menu-right ">
                                                    <a class="dropdown-item" href="{% url 'typo:typo-update' typo.id %}"><i
                                                            class="bx bx-edit-alt mr-1"></i>
                                                        {% trans 'ko`rish' %}</a>
                                                    <a class="dropdown-item removeButton" data-id="{{ typo.id }}"
                                                       href="{% url 'typo:typo-delete' typo.id %}"><i
                                                            class="bx bx-trash mr-1"></i>
                                                        {% trans 'o‘chirish' %}</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            {% if objects.has_other_pages %}

                                <nav aria-label="Page navigation example">
                                    <ul class="pagination mt-2 ml-2">
                                        {% if objects.has_previous %}
                                            <li class="page-item previous"><a class="page-link"
                                                                              href="?page={{ objects.previous_page_number }}">
                                                <i class="bx bx-chevron-left"></i>
                                            </a></li>
                                        {% else %}

                                            <li class="page-item previous disabled"><a class="page-link" href="">
                                                <i class="bx bx-chevron-left"></i>
                                            </a></li>
                                        {% endif %}
                                        {% for n in objects.paginator.page_range %}
                                            {% if objects.number == n %}
                                                <li class="page-item active" aria-current="page"><a class="page-link"
                                                                                                    href="#">{{ n }}</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item"><a class="page-link"
                                                                         href="?page={{ n }}">{{ n }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if objects.has_next %}

                                            <li class="page-item next"><a class="page-link"
                                                                          href="?page={{ objects.next_page_number }}">
                                                <i class="bx bx-chevron-right"></i>
                                            </a></li>
                                        {% else %}
                                            <li class="page-item next disabled"><a class="page-link" href="#">
                                                <i class="bx bx-chevron-right"></i>
                                            </a></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            {% endif %}

                        </div>
                        <!-- datatable ends -->
                    </div>
                </section>
                <!-- table Transactions end -->
            </div>
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
{% endblock %}

{% block js %}
    <style>
        .amallar {
            padding-bottom: 100px;
        }
    </style>
    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/datatables.checkboxes.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'back/app-assets/vendors/js/tables/datatable/responsive.bootstrap.min.js' %}"></script>
    <!-- END: Page Vendor JS-->
    <!-- BEGIN: Page JS-->
    <script src="{% static 'back/app-assets/js/scripts/pages/app-invoice.js' %}"></script>
    <!-- END: Page JS-->
    {#    <script>#}
    {#        $(document).ready(function () {#}
    {#            $('#table-extended-transactions').DataTable();#}
    {#        });#}
    {#    </script>#}

{% endblock %}